version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - /data/database:/var/lib/mysql
       - /data/.secrets:/var/secrets
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /var/secrets/.secret_db

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER_FILE: /var/secrets/.secret_wp_db_user
       WORDPRESS_DB_PASSWORD_FILE: /var/secrets/.secret_wp_db_pwd
       WORDPRESS_DB_NAME_FILE: /var/secrets/.secret_wp_db_name
     volumes:
      - /data/wordpress:/var/www/html
      - /data/.secrets:/var/secrets
volumes:
    db_data: 
    wordpress:
